### ISSUE TITLE
Make menu responsive

### ISSUE THREAD

**Issue by MillerPr** [helenaam/ochre-templates#1]
### The navbar should collapse on a small screen

The collapsing menu is sometimes called a hamburger menu, I suppose because the three horizontal lines are supposed to look like a bun and burger.  🍔 

There are a lot of tutorials out there, but here's the basic documentation:
https://getbootstrap.com/docs/4.1/components/navbar/
https://www.w3schools.com/bootstrap/bootstrap_navbar.asp

Thanks @helenaam !

**Comment by helenaam** [comment]
I made it so that the navbar is collapsed on smaller screens where it doesn't fit across the top.

**Comment by MillerPr** [comment]
The collapsed navbar looks perfect. Great job! 🥇
